import type { Question } from './types';

export const questions: Question[] = [
  // ── E / I axis (Q1–Q12) ──
  {
    id: 1,
    text: '週末の理想的な過ごし方は？',
    axis: 'EI',
    optionA: { text: '友達とにぎやかに過ごす', direction: 'E' },
    optionB: { text: '家でゆっくりリチャージする', direction: 'I' },
  },
  {
    id: 2,
    text: '初対面の人が多い場所に行ったとき？',
    axis: 'EI',
    optionA: { text: '積極的に話しかけて仲良くなる', direction: 'E' },
    optionB: { text: '様子を見ながら徐々に打ち解ける', direction: 'I' },
  },
  {
    id: 3,
    text: '大人数のパーティーに参加した帰り道は？',
    axis: 'EI',
    optionA: { text: '楽しかった！まだまだ元気', direction: 'E' },
    optionB: { text: '疲れた…家でゆっくりしたい', direction: 'I' },
  },
  {
    id: 4,
    text: '友達との連絡手段として好きなのは？',
    axis: 'EI',
    optionA: { text: '電話でリアルタイムに話したい', direction: 'E' },
    optionB: { text: 'LINEで自分のペースでやりとりしたい', direction: 'I' },
  },
  {
    id: 5,
    text: '休日に一人きりでいると？',
    axis: 'EI',
    optionA: { text: '退屈して誰かに連絡したくなる', direction: 'E' },
    optionB: { text: '一人時間を満喫できる', direction: 'I' },
  },
  {
    id: 6,
    text: '悩みが生じたとき、あなたは？',
    axis: 'EI',
    optionA: { text: '誰かに話して気持ちを整理する', direction: 'E' },
    optionB: { text: '一人でじっくり考え込む', direction: 'I' },
  },
  {
    id: 7,
    text: '知らない人ばかりのグループに入るのは？',
    axis: 'EI',
    optionA: { text: '新しい出会いにワクワクする', direction: 'E' },
    optionB: { text: '少し緊張するが慣れれば大丈夫', direction: 'I' },
  },
  {
    id: 8,
    text: '何かを考えるとき、あなたは？',
    axis: 'EI',
    optionA: { text: '声に出しながら考えるほうがまとまる', direction: 'E' },
    optionB: { text: '頭の中で整理してからまとめて話す', direction: 'I' },
  },
  {
    id: 9,
    text: '友人関係の広さは？',
    axis: 'EI',
    optionA: { text: '広く浅く、たくさんの人と繋がりたい', direction: 'E' },
    optionB: { text: '狭く深く、信頼できる少数と繋がりたい', direction: 'I' },
  },
  {
    id: 10,
    text: 'エネルギーをもらえると感じるのは？',
    axis: 'EI',
    optionA: { text: '人と話したり過ごしたりするとき', direction: 'E' },
    optionB: { text: '一人でゆっくり過ごせるとき', direction: 'I' },
  },
  {
    id: 11,
    text: '旅行先では？',
    axis: 'EI',
    optionA: { text: '現地の人や旅行者と積極的に話す', direction: 'E' },
    optionB: { text: '自分たちのペースでのんびり楽しむ', direction: 'I' },
  },
  {
    id: 12,
    text: 'SNSの使い方は？',
    axis: 'EI',
    optionA: { text: '積極的に発信している', direction: 'E' },
    optionB: { text: '見る専がほとんど', direction: 'I' },
  },

  // ── S / N axis (Q13–Q25) ──
  {
    id: 13,
    text: '新しいことを学ぶとき、あなたは？',
    axis: 'SN',
    optionA: { text: '基礎からステップを踏んで学ぶ', direction: 'S' },
    optionB: { text: 'まず全体像をつかんでから細部を学ぶ', direction: 'N' },
  },
  {
    id: 14,
    text: '判断の基準にするのは？',
    axis: 'SN',
    optionA: { text: '実際にあったこと・データ・実績', direction: 'S' },
    optionB: { text: '予感・ひらめき・可能性', direction: 'N' },
  },
  {
    id: 15,
    text: '好きな読み物は？',
    axis: 'SN',
    optionA: { text: '役立つ具体的な情報（ハウツーやニュース）', direction: 'S' },
    optionB: { text: '想像を膨らませるもの（小説・哲学・SF）', direction: 'N' },
  },
  {
    id: 16,
    text: '料理をするとき、あなたは？',
    axis: 'SN',
    optionA: { text: 'レシピ通りに正確に作る', direction: 'S' },
    optionB: { text: '自分なりのアレンジを加えてみる', direction: 'N' },
  },
  {
    id: 17,
    text: '好きな会話の内容は？',
    axis: 'SN',
    optionA: { text: '実際に起きた出来事や体験談', direction: 'S' },
    optionB: { text: '可能性や「もしも」の話・未来の話', direction: 'N' },
  },
  {
    id: 18,
    text: '問題を解決するとき、あなたは？',
    axis: 'SN',
    optionA: { text: '実績がある方法・過去の経験を参考にする', direction: 'S' },
    optionB: { text: '新しいアプローチや独自のやり方を試みる', direction: 'N' },
  },
  {
    id: 19,
    text: '現実と理想、どちらをより意識する？',
    axis: 'SN',
    optionA: { text: '現実を見て判断することが大事', direction: 'S' },
    optionB: { text: '理想を持ち続けることが大事', direction: 'N' },
  },
  {
    id: 20,
    text: '物事を見るとき、どちらに注目する？',
    axis: 'SN',
    optionA: { text: '細かいディテールや具体的な事実', direction: 'S' },
    optionB: { text: '全体の流れやパターン・意味', direction: 'N' },
  },
  {
    id: 21,
    text: '過去と未来、どちらをより意識する？',
    axis: 'SN',
    optionA: { text: '過去の経験から学ぶことを重視する', direction: 'S' },
    optionB: { text: '未来の可能性に目を向けることを重視する', direction: 'N' },
  },
  {
    id: 22,
    text: '言葉の使い方として自然なのは？',
    axis: 'SN',
    optionA: { text: '言葉をそのままの意味で使う', direction: 'S' },
    optionB: { text: '比喩や象徴的な表現が好き', direction: 'N' },
  },
  {
    id: 23,
    text: '趣味を選ぶとき、あなたは？',
    axis: 'SN',
    optionA: { text: '実用的で身になるものを選ぶ', direction: 'S' },
    optionB: { text: '好奇心の赴くままに選ぶ', direction: 'N' },
  },
  {
    id: 24,
    text: 'ひらめきや直感は？',
    axis: 'SN',
    optionA: { text: 'あまりない。考えて答えを出すほう', direction: 'S' },
    optionB: { text: 'よくひらめく。直感を信じるほう', direction: 'N' },
  },
  {
    id: 25,
    text: '好きな映画・ドラマのジャンルは？',
    axis: 'SN',
    optionA: { text: 'リアルで現実的な人間ドラマ', direction: 'S' },
    optionB: { text: 'SF・ファンタジーなど非現実的な世界観', direction: 'N' },
  },

  // ── T / F axis (Q26–Q37) ──
  {
    id: 26,
    text: '何かを決めるとき、あなたは？',
    axis: 'TF',
    optionA: { text: '論理的に分析して結論を出す', direction: 'T' },
    optionB: { text: '自分の気持ちや価値観を大事にして決める', direction: 'F' },
  },
  {
    id: 27,
    text: '友達から相談されたとき、あなたは？',
    axis: 'TF',
    optionA: { text: '解決策や具体的なアドバイスを提案する', direction: 'T' },
    optionB: { text: 'まず相手の気持ちに寄り添って共感する', direction: 'F' },
  },
  {
    id: 28,
    text: '「公平」とは、あなたにとって？',
    axis: 'TF',
    optionA: { text: '全員に同じルールを適用すること', direction: 'T' },
    optionB: { text: 'それぞれの状況に応じて柔軟に対応すること', direction: 'F' },
  },
  {
    id: 29,
    text: '批判やフィードバックを受けたとき？',
    axis: 'TF',
    optionA: { text: '内容が正しければ感情を抑えて受け入れる', direction: 'T' },
    optionB: { text: '内容より伝え方や気持ちが気になる', direction: 'F' },
  },
  {
    id: 30,
    text: '知的な議論は好きですか？',
    axis: 'TF',
    optionA: { text: '論理的な議論で白黒つけるのが好き', direction: 'T' },
    optionB: { text: '論争より理解し合える対話が好き', direction: 'F' },
  },
  {
    id: 31,
    text: 'より大事にするのは？',
    axis: 'TF',
    optionA: { text: '真実・事実・客観性', direction: 'T' },
    optionB: { text: '人の気持ち・関係性・調和', direction: 'F' },
  },
  {
    id: 32,
    text: '仕事や作業で重視するのは？',
    axis: 'TF',
    optionA: { text: '効率・成果・正確さ', direction: 'T' },
    optionB: { text: 'チームの雰囲気・人間関係の良さ', direction: 'F' },
  },
  {
    id: 33,
    text: '言われて嬉しい褒め言葉は？',
    axis: 'TF',
    optionA: { text: '「能力が高い」「分析力がある」', direction: 'T' },
    optionB: { text: '「優しい」「思いやりがある」', direction: 'F' },
  },
  {
    id: 34,
    text: '感情を表に出すほうですか？',
    axis: 'TF',
    optionA: { text: '必要なときにしか表さない', direction: 'T' },
    optionB: { text: '感情が自然と顔や言葉に出る', direction: 'F' },
  },
  {
    id: 35,
    text: '映画やドラマを観るとき？',
    axis: 'TF',
    optionA: { text: 'ストーリーの矛盾や論理的な不整合が気になる', direction: 'T' },
    optionB: { text: 'キャラクターの感情に強く感情移入する', direction: 'F' },
  },
  {
    id: 36,
    text: 'グループでの自分の役割は？',
    axis: 'TF',
    optionA: { text: '分析・計画・問題解決の担当になりがち', direction: 'T' },
    optionB: { text: 'まとめ役・サポート役になりがち', direction: 'F' },
  },
  {
    id: 37,
    text: '「正しいこと」と「良いこと」どちらが大事？',
    axis: 'TF',
    optionA: { text: '正しいこと（論理的・客観的に正確なこと）', direction: 'T' },
    optionB: { text: '良いこと（人々にとって幸福なこと）', direction: 'F' },
  },

  // ── J / P axis (Q38–Q50) ──
  {
    id: 38,
    text: '締め切りに対するスタンスは？',
    axis: 'JP',
    optionA: { text: '余裕を持って早めに終わらせる', direction: 'J' },
    optionB: { text: '締め切り直前に集中力を発揮する', direction: 'P' },
  },
  {
    id: 39,
    text: '旅行の計画を立てるとき？',
    axis: 'JP',
    optionA: { text: '宿・交通・スケジュールを全部決めてから行く', direction: 'J' },
    optionB: { text: '方向性だけ決めて、あとは行き当たりばったり', direction: 'P' },
  },
  {
    id: 40,
    text: '自分の部屋や机の状態は？',
    axis: 'JP',
    optionA: { text: '整理整頓されていてすっきりしている', direction: 'J' },
    optionB: { text: '自分なりの秩序で、ちょっと散らかっている', direction: 'P' },
  },
  {
    id: 41,
    text: '予定が急に変更になると？',
    axis: 'JP',
    optionA: { text: '困る、できれば変えないでほしい', direction: 'J' },
    optionB: { text: '柔軟に対応できる、むしろアドベンチャー', direction: 'P' },
  },
  {
    id: 42,
    text: '複数のタスクがあるとき？',
    axis: 'JP',
    optionA: { text: '優先順位をつけて一つずつ片付ける', direction: 'J' },
    optionB: { text: '気分に合わせて気が向いたものを進める', direction: 'P' },
  },
  {
    id: 43,
    text: '決断をするとき、あなたは？',
    axis: 'JP',
    optionA: { text: '早めに決めてすっきりしたい', direction: 'J' },
    optionB: { text: 'ギリギリまで情報を集めて選択肢を残したい', direction: 'P' },
  },
  {
    id: 44,
    text: '好きな休日の過ごし方は？',
    axis: 'JP',
    optionA: { text: 'あらかじめ計画を立てて行動する', direction: 'J' },
    optionB: { text: '朝起きてから気分で決める', direction: 'P' },
  },
  {
    id: 45,
    text: '買い物をするとき？',
    axis: 'JP',
    optionA: { text: '事前に調べて、決めてから買いに行く', direction: 'J' },
    optionB: { text: 'ピンときたものを見てから決める', direction: 'P' },
  },
  {
    id: 46,
    text: 'To-doリストは？',
    axis: 'JP',
    optionA: { text: 'よく作る、達成するのが好き', direction: 'J' },
    optionB: { text: 'あまり作らない、必要なら頭の中にある', direction: 'P' },
  },
  {
    id: 47,
    text: '仕事や勉強が終わるとき？',
    axis: 'JP',
    optionA: { text: 'きちんと完了させてから切り上げたい', direction: 'J' },
    optionB: { text: '途中でも時間が来たら切り上げる', direction: 'P' },
  },
  {
    id: 48,
    text: '新しい情報が来て判断を変えるとき？',
    axis: 'JP',
    optionA: { text: '一度決めたことを変えるのは慎重', direction: 'J' },
    optionB: { text: '柔軟に最新情報を反映して更新できる', direction: 'P' },
  },
  {
    id: 49,
    text: '計画通りにいかないとき？',
    axis: 'JP',
    optionA: { text: 'ストレスを感じる、なるべく計画に戻したい', direction: 'J' },
    optionB: { text: 'なんとかなると思える、流れに乗れる', direction: 'P' },
  },
  {
    id: 50,
    text: 'プロジェクトを始めるとき、まず？',
    axis: 'JP',
    optionA: { text: '詳細なスケジュールと役割分担を決める', direction: 'J' },
    optionB: { text: 'とりあえずやりながら考える', direction: 'P' },
  },
];
